import { chromium } from 'playwright';
const BASE='http://127.0.0.1:5080', EXE=process.env.SK_CHROME || undefined;
const b=await chromium.launch({executablePath:EXE,headless:true});
const p=await (await b.newContext({viewport:{width:1400,height:1100}})).newPage();
p.on('pageerror',e=>console.log('ERR',e.message));
await p.goto(BASE+'/admin/'); await p.fill('#password','test123'); await p.click('#loginForm button[type=submit]');
await p.waitForSelector('#app:not(.hidden)',{timeout:8000});
let m=p.locator('.modal button',{hasText:'Отказаться от черновика'}); if(await m.count()) await m.click();
await p.evaluate(async()=>{await fetch('/api/admin/document',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'П',signPrompt:'x',thankYouText:'x',idleReturnSec:0,pages:[{headingRuns:[{text:'A'}],blocks:[{runs:[{text:'текст'}],ord:0}],checkboxes:[{key:'da',label:'Да',required:false,ord:1}],includeDynamic:false}]})});});
await p.reload(); await p.waitForSelector('#app:not(.hidden)',{timeout:8000});
m=p.locator('.modal button',{hasText:'Отказаться от черновика'}); if(await m.count()) await m.click();
await p.click('.tab[data-tab="document"]'); await p.waitForTimeout(600);
console.log('ДО вставки:', JSON.stringify(await p.evaluate(()=>Array.from(document.querySelectorAll('[data-role="pagecard"] [data-role="blockcard"]')).map(c=>({mode:c.getAttribute('data-mode'),sel:!!c.querySelector('[data-role="blocklist"]'),disp:c.querySelector('[data-role="blocklist"]')?getComputedStyle(c.querySelector('[data-role="blocklist"]').parentElement).display:'-'})))));
await p.locator('[data-role="pagecard"] .insert-chip').last().click(); await p.waitForTimeout(200);
const было=await p.evaluate(()=>document.querySelectorAll('[data-role="pagecard"] .page-item').length);
await p.locator('button',{hasText:'Таблица'}).first().click();
await p.waitForTimeout(100);
const сразу=await p.evaluate(()=>document.querySelectorAll('[data-role="pagecard"] .page-item').length);
await p.waitForTimeout(500);
const потом=await p.evaluate(()=>document.querySelectorAll('[data-role="pagecard"] .page-item').length);
console.log('элементов было/сразу/потом:', было, сразу, потом);
console.log('ПОСЛЕ таблицы:', JSON.stringify(await p.evaluate(()=>Array.from(document.querySelectorAll('[data-role="pagecard"] [data-role="blockcard"]')).map(c=>({mode:c.getAttribute('data-mode'),special:c.getAttribute('data-special')||'',disp:c.querySelector('[data-role="blocklist"]')?getComputedStyle(c.querySelector('[data-role="blocklist"]').parentElement).display:'нет'})))));
await b.close();
