import { chromium } from 'playwright';
const BASE='http://127.0.0.1:5080', EXE=process.env.SK_CHROME || undefined;
const b=await chromium.launch({executablePath:EXE,headless:true});
const p=await (await b.newContext({viewport:{width:1400,height:1100}})).newPage();
p.on('pageerror',e=>console.log('ERR',e.message));
await p.goto(BASE+'/admin/'); await p.fill('#password','test123'); await p.click('#loginForm button[type=submit]');
await p.waitForSelector('#app:not(.hidden)',{timeout:8000});
let m=p.locator('.modal button',{hasText:'Отказаться от черновика'}); if(await m.count()) await m.click();
await p.evaluate(async()=>{await fetch('/api/admin/document',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'П',signPrompt:'x',thankYouText:'x',idleReturnSec:0,pages:[{headingRuns:[{text:'A'}],blocks:[{runs:[{text:'ВАЖНОЕ слово'}],ord:0}],checkboxes:[],includeDynamic:false}]})});});
await p.reload(); await p.waitForSelector('#app:not(.hidden)',{timeout:8000});
m=p.locator('.modal button',{hasText:'Отказаться от черновика'}); if(await m.count()) await m.click();
await p.click('.tab[data-tab="document"]'); await p.waitForTimeout(600);
const ред=p.locator('[data-role="pagecard"] [data-role="blockbody"]').first();
await ред.click();
await p.evaluate(()=>{const ed=document.querySelector('[data-role="pagecard"] [data-role="blockbody"]');
  const узлы=[];(function w(n){for(const c of n.childNodes){if(c.nodeType===3)узлы.push(c);else w(c);} })(ed);
  const r=document.createRange(); r.setStart(узлы[0],0); r.setEnd(узлы[0],6);
  const s=window.getSelection(); s.removeAllRanges(); s.addRange(r);});
await p.waitForTimeout(300);
console.log('панель есть:', await p.locator('[data-role="rtbar"]').count(), 'видима:', await p.locator('[data-role="rtbar"]').isVisible().catch(()=>'нет'));
console.log('образцов маркера:', await p.locator('.rt-swatch-mark').count());
await p.locator('.rt-swatch-mark').first().click();
await p.waitForTimeout(400);
console.log('разметка:', (await ред.innerHTML()).slice(0,300));
// Перехватываем тело запроса сохранения: так видно, что именно уходит на сервер.
await p.evaluate(()=>{const f=window.fetch;window.__sent=null;window.fetch=function(u,o){if(String(u).indexOf('/api/admin/document')>=0&&o&&o.method==='PUT')window.__sent=o.body;return f.apply(this,arguments);};});
await p.click('#saveDocument'); await p.waitForTimeout(800);
const тело=await p.evaluate(()=>window.__sent);
const doc=JSON.parse(тело||'{}');
console.log('ушло на сервер:', JSON.stringify((doc.pages&&doc.pages[0]&&doc.pages[0].blocks&&doc.pages[0].blocks[0]||{}).runs));
console.log('вернулось:', JSON.stringify((await p.evaluate(async()=>(await fetch('/api/admin/document',{credentials:'same-origin'})).json())).pages[0].blocks[0].runs));
await b.close();
